Access to Electricity                   Purple book pg 41, 17.6.15
=================================================================
ref: rpubs.com/justmarkham/dplyr-tutorial
    data.worldbank.org  

population
==========
Create table of population for each region / income level combination
```{r}
library(jsonlite)
library(dplyr)
library(tidyr)
populationUrl <- 'http://api.worldbank.org/countries/indicators/SP.POP.TOTL?per_page=1000&date=2013&format=json'
populationFile <- "/Users/jamesmungall/MyR/GettingCleaningData/data/worldBank/population/population.json"
download.file(populationUrl, destfile = populationFile, method = "curl")
jsonPopulation <- fromJSON(populationFile)
population <- jsonPopulation[[2]][-(1:34),] %>%
  flatten() %>% tbl_df() %>%
  transmute(country.value, pop=as.numeric(value))
```
countries
=========
```{r}
countriesUrl <- 'http://api.worldbank.org/countries?format=json&per_page=1000'
countriesFile <- "/Users/jamesmungall/MyR/GettingCleaningData/data/worldBank/countries.json"
download.file(countriesUrl, destfile = countriesFile, method = "curl")
jsonData <- fromJSON(countriesFile)
countries <- jsonData[[2]] %>%
  flatten() %>% tbl_df() %>%
  select(country.value=name,region.id,incomeLevel.id)
```  
popRegionIncome
===============
combine population and region/incomeLevel data
```{r}
popRegionIncome <- left_join(population,countries,by='country.value')
View(popRegionIncome)
```

accessToElectriciy
==================
Turn electricity percentages into number of persons
```{r}

elecUrl<-'http://api.worldbank.org/countries/indicators/EG.ELC.ACCS.ZS?per_page=1000&date=2010&format=json'
elecFile <- "/Users/jamesmungall/MyR/GettingCleaningData/data/worldBank/accessToElectricity/accessToElectricity.json"
download.file(elecUrl, destfile = elecFile, method = "curl")
elecData <- fromJSON(elecFile)
accessToElectricity <- elecData[[2]][-(1:34),] %>% flatten() %>% tbl_df() %>%
  transmute(country.value, elecPerc = as.numeric(value))
View(accessToElectricity)
```

popElec
======
```{r}
popElec <-  left_join(popRegionIncome,accessToElectricity,by='country.value') %>%
  mutate(elecPop = pop * elecPerc/100) %>%
  group_by(region.id,incomeLevel.id) %>%
  summarise_each(funs(sum), totalPop=pop,elecPop) %>%
  mutate(elecPerc = (100 * elecPop / totalPop)) %>%
  select(region.id,incomeLevel.id,elecPerc) %>%
  spread(key=region.id,value=elecPerc)
View(popElec)
```

